export { default as Layout } from './Layout.vue'
export { default as Sidebar } from './Sidebar.vue'
export { default as Header } from './Header.vue'
export { default as AddressBar } from './AddressBar.vue'
export { default as WinBtn } from './WinBtn.vue'
export { default as TabBar } from './TabBar.vue'
// export { default as Footer } from './Footer.vue'