/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    2: typeof import('./src/components/Layout/Header copy 2.vue')['default']
    AddressBar: typeof import('./src/components/Layout/AddressBar.vue')['default']
    AInput: typeof import('ant-design-vue/es')['Input']
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    ATabs: typeof import('ant-design-vue/es')['Tabs']
    copy: typeof import('./src/components/Layout/Header copy.vue')['default']
    Header: typeof import('./src/components/Layout/Header.vue')['default']
    'Header copy': typeof import('./src/components/Layout/Header copy.vue')['default']
    'Header copy 2': typeof import('./src/components/Layout/Header copy 2.vue')['default']
    Layout: typeof import('./src/components/Layout/Layout.vue')['default']
    MoreTabs: typeof import('./src/components/pro-ui/pro-tabs/MoreTabs.vue')['default']
    ProTabs: typeof import('./src/components/pro-ui/pro-tabs/ProTabs.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/Layout/Sidebar.vue')['default']
    Tabs: typeof import('./src/components/Layout/Tabs.vue')['default']
    Versions: typeof import('./src/components/Versions.vue')['default']
    WinBtn: typeof import('./src/components/Layout/WinBtn.vue')['default']
  }
}
