/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    2: typeof import('./src/components/Layout/Header copy 2.vue')['default']
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    AButton: typeof import('ant-design-vue/es')['Button']
    AddressBar: typeof import('./src/components/Layout/AddressBar.vue')['default']
    AInput: typeof import('ant-design-vue/es')['Input']
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    ATabs: typeof import('ant-design-vue/es')['Tabs']
    copy: typeof import('./src/components/Layout/Header copy.vue')['default']
    DynamicTabContent: typeof import('./src/components/Layout/DynamicTabContent.vue')['default']
    Header: typeof import('./src/components/Layout/Header.vue')['default']
    Layout: typeof import('./src/components/Layout/Layout.vue')['default']
    MoreTabs: typeof import('./src/components/pro-ui/pro-tabs/MoreTabs.vue')['default']
    ProContextMenu: typeof import('./src/components/pro-ui/pro-context-menu/ProContextMenu.vue')['default']
    ProOptionSelect: typeof import('./src/components/pro-ui/pro-option-select/ProOptionSelect.vue')['default']
    ProPopup: typeof import('./src/components/pro-ui/pro-popup/ProPopup.vue')['default']
    ProTabs: typeof import('./src/components/pro-ui/pro-tabs/ProTabs.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/Layout/Sidebar.vue')['default']
    TabBar: typeof import('./src/components/Layout/TabBar.vue')['default']
    Tabs: typeof import('./src/components/Layout/Tabs.vue')['default']
    Versions: typeof import('./src/components/Versions.vue')['default']
    WinBtn: typeof import('./src/components/Layout/WinBtn.vue')['default']
  }
}
